# Site settings
title: Blog
subtitle: of Brian
email: rayshoo92@gmail.com
description: Brian Choi의 블로그에 오신것을 환영합니다
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rayshoo.github.io/" # the base hostname & protocol for your site
author: Brian Choi
street_address: 
city: Seoul
state: 
zip_code: 
country: Republic of Korea
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/rayshoo
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
