# Site settings
title: Terminal
subtitle: 
email: fire@dragonz.dev
description: dragonz.dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "rayshoo.github.io" # the base hostname & protocol for your site
author: Brian Choi
country: Republic of Korea
phone:
slack: rayshoo92@gmail.com

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/rayshoo
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
highlighter: rouge

# url settings
permalink: /:categories/:title